services:
  medocker-web:
    build:
      context: .
      dockerfile: Dockerfile
    image: medocker-web
    container_name: medocker-web
    environment:
      - PORT=${PORT:-9876}
      - HOST=${HOST:-0.0.0.0}
      - FLASK_ENV=${FLASK_ENV:-production}
      - SECRET_KEY=${SECRET_KEY:-generate_a_strong_secret_key}
      - SECURE_COOKIES=${SECURE_COOKIES:-true}
      - CORS_ORIGINS=${CORS_ORIGINS:-*}
      - THREADS=${THREADS:-20}
    volumes:
      - medocker_config:/app/config
      - ${DATA_VOLUME:-medocker_data}:/app/data
    ports:
      - "${BIND_ADDRESS:-0.0.0.0}:9876:9876"
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9876/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  medocker_config:
    driver: local
  medocker_data:
    driver: local

networks:
  default:
    driver: bridge 